<a href="https://colab.research.google.com/github/Shravanie13/ml/blob/main/workshopday1_gen_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [8]:
df=pd.read_csv("homeprices.csv")  #to check the column

In [9]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [5]:
df.columns

Index(['town', 'area', 'price'], dtype='object')

In [7]:
df.shape

(13, 3)

In [11]:
df.town.value_counts()

town
monroe township    5
west windsor       4
robinsville        4
Name: count, dtype: int64

In [12]:
df.describe()

area          price
count    13.000000      13.000000
mean   3146.153846  629230.769231
std     453.900475   57621.109914
min    2600.000000  550000.000000
25%    2800.000000  585000.000000
50%    3100.000000  615000.000000
75%    3600.000000  680000.000000
max    4000.000000  725000.000000

In [13]:
dummies=pd.get_dummies(df.town) #encoding converting categories to numerical data
dummies

monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [15]:
merged=pd.concat([df,dummies],axis="columns")  #inplace true=1 can be used as one more that nmainmg the one in the variable

In [16]:
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [19]:
merged=merged.drop(["town"],axis="columns")

In [21]:
merged

area   price  monroe township  robinsville  west windsor
0   2600  550000             True        False         False
1   3000  565000             True        False         False
2   3200  610000             True        False         False
3   3600  680000             True        False         False
4   4000  725000             True        False         False
5   2600  585000            False        False          True
6   2800  615000            False        False          True
7   3300  650000            False        False          True
8   3600  710000            False        False          True
9   2600  575000            False         True         False
10  2900  600000            False         True         False
11  3100  620000            False         True         False
12  3600  695000            False         True         False

When one variable can be predicted using other variables, it is called multicollinearity.

For example, if you know the values of California and Georgia, you can easily determine the value of New Jersey. This means these state variables are dependent on each other.

In such cases, linear regression won’t work correctly because the model struggles with redundant information. To fix this, you should remove one of the columns to avoid issues.


In [22]:
merged=merged.drop(["west windsor"],axis="columns")

In [23]:
merged

area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [29]:
x = merged.drop(["price"],axis="columns")             #input features data

In [28]:
y = merged.price #output variable

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 42)

In [32]:
x_train.shape

(9, 3)

In [33]:
x_test.shape

(4, 3)

In [35]:
model=LinearRegression()

In [36]:
model.fit(x_train,y_train)       #model.fit or fit method is used to train the model.

LinearRegression()

In [37]:
y_test_pred=model.predict(x_test)

In [38]:
y_test

11    620000
9     575000
0     550000
8     710000
Name: price, dtype: int64

In [39]:
y_test_pred

array([626917.80821918, 558310.50228312, 528367.57990869, 712716.89497716])

In [40]:
model.score(x_test,y_test)


0.9460789560707652

In [41]:
model.score(x_train,y_train)

0.9464717800476193

In [ ]:
###predict the house price of a house with the following features
# area=2500
# town=robinsville


In [46]:
new_data = [2500,0,1]

In [47]:
model.predict([new_data])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([544589.04109591])

In [48]:
new_data1=[3000,0,0]

In [49]:
model.predict([new_data1])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([630388.12785389])